name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install selenium

    - name: Download ChromeDriver
      run: |
        sudo apt-get install -y unzip
        wget -N https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip -d /usr/local/bin/
        rm chromedriver_linux64.zip

    - name: Install ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-chromedriver

    - name: Create and activate virtual environment
      run: |
        python -m venv .venv
        source .venv/bin/activate

    - name: Run CGV script
      run: |
        source .venv/bin/activate
        python /home/runner/work/CGV.APPS/CGV.APPS/cgv.py

    # Additional commands
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        source .venv/bin/activate
        pip install -r requirements.txt

    - name: Run script
      run: |
        source .venv/bin/activate
        python C:\Users\user\Downloads\CGV.APPS\cgv.py