name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 480  # 최대 실행 시간을 480분으로 설정

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run CGV script
      run: python /home/runner/work/CGV.APPS/CGV.APPS/cgv.py


      
